include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

generate-node-address = false

aws {
  region = elasticmq
  accountId = 000000000000
}

queues {
  glint {
    deadLettersQueue {
      name = "glint-dead-letter"
      maxReceiveCount = 5
    }
  }
  glint-dead-letter { }
}

messages-storage {
  enabled = true
}
